name: Update File Tree

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    permissions:
      contents: write  

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run Python script
        run: python "Test Tree/file_tree_maker.py" 

      - name: Commit new txt file
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add "Test Tree/file_tree.txt"  # Adjust this path to where your .txt file is saved
          git commit -m "Add updated .txt file"
          
          # Push changes using the GITHUB_TOKEN
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
