name: Update File Tree

on:
  push:
    branches:
      - main  

jobs:
  update-tree:
    runs-on: ubuntu-latest  

    steps:
      - name: Check out repository
        uses: actions/checkout@v2  

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # If you have any dependencies, you can install them here
          # For example: pip install -r requirements.txt

      - name: Run file tree generator script
        run: |
          python file_tree_maker.py  # Run your Python script to update file_tree.txt

      - name: Commit and push updated file_tree.txt
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add file_tree.txt
          git commit -m "Update file tree"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
