name: Update File Tree

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Find and run the file_tree_maker.py script
        run: |
          file_path=$(find . -name "file_tree_maker.py" -print -quit)
          if [ -z "$file_path" ]; then
            echo "file_tree_maker.py not found!"
            exit 1
          else
            echo "Found file_tree_maker.py at $file_path"
            python "$file_path"
          fi

      - name: Find the file_tree.txt file
        id: find_file
        run: |
          file_tree_path=$(find . -name "file_tree.txt" -print -quit)
          if [ -z "$file_tree_path" ]; then
            echo "file_tree.txt not found!"
            exit 1
          else
            echo "Found file_tree.txt at $file_tree_path"
            echo "::set-output name=file_tree_path::$file_tree_path"
          fi

      - name: Check if there are changes to commit
        id: changes
        run: |
          git diff --exit-code || echo "Changes detected"

      - name: Commit new txt file
        if: steps.changes.outputs.changes == 'Changes detected'
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          
          git add "${{ steps.find_file.outputs.file_tree_path }}"
          git commit -m "Add updated file_tree.txt file"
          
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
