on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    permissions:
      contents: write  

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Find and run Python script
        run: |
          SCRIPT_PATH=$(find . -type f -name "file_tree_maker.py")
          if [ -n "$SCRIPT_PATH" ]; then
            python "$SCRIPT_PATH"
          else
            echo "file_tree_maker.py not found"
            exit 1
          fi


      - name: Commit new txt file
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          
          FILE_PATH=$(find . -type f -name "file_tree.txt")
          
          if [ -n "$FILE_PATH" ]; then
            git add "$FILE_PATH"
            git commit -m "Add updated file_tree.txt file"
            
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          else
            echo "file_tree.txt not found"
            exit 1
          fi

